---
  env:
    browser: true
    node: true
    jest: true
  extends:
    - airbnb
    - plugin:jsx-a11y/recommended
  plugins:
    - jsx-a11y
  settings:
    import/resolver: webpack
  parser: babel-eslint
  parserOptions:
    sourceType: module
    allowImportExportEverywhere: false
    codeFrame: false
  globals:
    window: false
    document: false
    shallowWithTheme: true
    mountWithTheme: true
